[package]
name = "rsh"
version = "0.1.0"
edition = "2021"

[dependencies]
nix="0.10.0"
whoami="1.5.2"
colored="2"
crossterm="0.28.1"
csv = "1.1"
chrono="0.4.39"
unicode-segmentation = "1.12.0"
nom = "5"
signal-hook = "0.3"
